#!/usr/bin/env python3

from __future__ import print_function

import re
import statistics
from math import log10, floor
import json

def round_to_significant_digits(x, n):
  return round(x, -int(floor(log10(abs(x)))) + (n - 1))

class NumberGroup:
  def __init__(self):
    self.raw_numbers = []

  def add(self, n):
    self.raw_numbers.append(n)
    return self

  @property
  def numbers(self):
    return [float(x) for x in self.raw_numbers]

  @classmethod
  def single(cls, n):
    return NumberGroup().add(n)

  def first(self):
    return self.raw_numbers[0]

  def are_identical(self):
    f = self.first()
    return all([x == f for x in self.raw_numbers])

def parse_numbers(s):
  def _parse_numbers(s):
    m = re.search(b"[0-9.]+", s)
    if m is None:
      return [(True, s)]
    prefix = s[:m.start()]
    number = m.group(0)
    return [(False, prefix), (True, number)] + _parse_numbers(s[m.end():])
  return [s for s in _parse_numbers(s) if s[1] != ""]

class NullFile:
  def write(self, d):
    pass

  def flush(self):
    pass

  def close(self):
    pass

class CommandRunner:
  def __init__(self, cmd, output):
    self.cmd = cmd
    self.output = output or NullFile()
    self.num_runs = 0
    self._print_header()

  def _print_header(self):
    self.output.write(
      json.dumps({"cmd": self.cmd}).encode('utf-8'))
    self.separator()

  def separator(self):
    self.output.write(b"\n" + b"-" * 10 + b"\n")
    self.output.flush()

  def run(self):
    out = subprocess.check_output(self.cmd)
    self.num_runs += 1
    self.output.write(out)
    self.separator()
    return out

  def close(self):
    self.output.close()


  @classmethod
  def parse(self, f):
    outputs = []
    lines = []
    for line in f:
      if line == b"-" * 10 + b"\n":
        outputs.append(b"".join(lines))
        lines = []
      else:
        lines.append(line)
    if lines:
      print("unexpected data after last output:")
      print(b"".join(lines).decode("utf-8"))
    metadata_blob = outputs.pop(0).decode("utf-8")
    metadata = json.loads(metadata_blob)
    return metadata, outputs

class CommandReplayer:
  def __init__(self, cmd, outputs):
    self.cmd = cmd
    self.outputs = outputs
    self.num_runs = len(outputs)

  def run(self):
    return self.outputs.pop(0)

  def close(self):
    pass

if __name__ == "__main__":
  import argparse
  import subprocess

  parser = argparse.ArgumentParser()
  parser.add_argument("--iters",
                      type=int,
                      default=1,
                      help="number of iterations to run command")
  parser.add_argument("-o", "--output",
                      default=None,
                      help="file to store captured output")
  parser.add_argument("-i", "--input",
                      default=None,
                      help="file with previous outputs to load")
  parser.add_argument("--mean-digits",
                      type=int,
                      default=3,
                      help="number of significant digits to print means to")
  parser.add_argument("--std-digits",
                      type=int,
                      default=2,
                      help="number of significant digits to print standard deviation to")

  args, command_args = parser.parse_known_args()

  if args.input:
    with open(args.input, 'rb') as f:
      metadata, outputs = CommandRunner.parse(f)
    command_args = metadata['cmd']
    runner = CommandReplayer(command_args, outputs)
    if args.iters == 1:
      args.iters = len(outputs)
  else:
    output_file = None
    if args.output:
      output_file = open(args.output, "wb")
    runner = CommandRunner(command_args, output_file)

  template = parse_numbers(runner.run())
  aggregated = [NumberGroup.single(x) if isnumber else x
                for (isnumber, x) in template]

  for _ in range(args.iters-1):
    output = parse_numbers(runner.run())
    for i, (isnumber, seg) in enumerate(output):
      tisnumber, tseg = template[i]
      aggregate = aggregated[i]
      if tisnumber:
        if isnumber:
          aggregated[i].add(seg)
        else:
          print("unexpected string\n{}".format(seg))
      else:
        if tseg != seg:
          print("unexpected output\n\n{}\n\nexpecting\n{}\n".format(seg, tseg))
  runner.close()

  for seg in aggregated:
    if type(seg) == NumberGroup:
      if seg.are_identical():
        print(seg.first().decode("utf-8"), end="")
        continue
      mean = round_to_significant_digits(statistics.mean(seg.numbers), args.mean_digits)
      stddev = round_to_significant_digits(statistics.stdev(seg.numbers), args.std_digits)
      print("{}±{}".format(mean, stddev), end="")
    else:
      print(seg.decode("utf-8"), end="")
  print("statistical:")
  print("{}\n{} runs".format(" ".join(runner.cmd), runner.num_runs))
